#!/bin/bash

# This file is public domain in the USA and all free countries.
# Elsewhere, consider it to be WTFPLv2. (wtfpl.net/txt/copying)

echo "Swearing is what i do best.
Which language would you like me to swear to ?"
read answer

bash readFile.sh $answer
